# Copyright 2024 The Gorilla Team and the Berkeley Function Calling Leaderboard authors
# Copyright 2024 Bytedance Ltd. and/or its affiliates
# SPDX-License-Identifier: Apache-2.0
#
# Adapted from https://github.com/ShishirPatil/gorilla
# (berkeley-function-call-leaderboard/bfcl_eval), licensed under Apache-2.0.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generate the verl tool-config YAML for BFCL v3 multi-turn tools.

Emits one entry per BFCL backend method (128 across 8 classes), each resolving
its schema from :mod:`verl.utils.bfcl_multiturn.tool_schemas` by ``function_name``
at load time. With ``--with_workbench`` it prepends the WorkBench tool entries so
a single ``tool_agent`` loop can serve both WorkBench and BFCL validation in one
run (per-sample ``extra_info.tool_selection`` restricts which subset each sample
actually sees). BFCL and WorkBench method names are globally unique, which this
script asserts.

Usage::

    python -m verl.utils.bfcl_multiturn.generate_tool_config \
        --with_workbench \
        --out examples/my_trainer/config/workbench_bfcl_tool_config.yaml
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../..")))

from verl.utils.bfcl_multiturn.tool_schemas import BFCL_TOOL_NAMES  # noqa: E402

_HEADER = (
    "# Auto-generated by verl/utils/bfcl_multiturn/generate_tool_config.py\n"
    "# One entry per BFCL backend method (+ optional WorkBench tools); schemas are\n"
    "# resolved via `function_name` at load time. Per-sample `extra_info.tool_selection`\n"
    "# restricts the advertised subset for each rollout.\n"
)


def _entry(class_name: str, function_name: str) -> str:
    return (
        f'  - class_name: "{class_name}"\n'
        f"    config:\n"
        f"      type: native\n"
        f'      function_name: "{function_name}"\n'
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True, help="Output YAML path.")
    parser.add_argument(
        "--with_workbench",
        action="store_true",
        help="Prepend WorkBench tool entries so one config serves both domains.",
    )
    args = parser.parse_args()

    lines = [_HEADER, "tools:\n"]

    names_seen: set[str] = set()

    if args.with_workbench:
        from verl.utils.workbench.schemas import WORKBENCH_TOOL_NAMES

        for name in WORKBENCH_TOOL_NAMES:
            names_seen.add(name)
            lines.append(_entry("verl.tools.workbench_tool.WorkbenchTool", name))

    for name in BFCL_TOOL_NAMES:
        if name in names_seen:
            raise ValueError(f"Tool name collision between WorkBench and BFCL: '{name}'")
        names_seen.add(name)
        lines.append(_entry("verl.tools.bfcl_tool.BfclTool", name))

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        f.write("".join(lines))

    n_bfcl = len(BFCL_TOOL_NAMES)
    print(f"Wrote {len(names_seen)} tool entries ({n_bfcl} BFCL) -> {args.out}")


if __name__ == "__main__":
    main()
